# Generated by Django 3.2.9 on 2022-06-06 10:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MyUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Имя')),
                ('pin_code', models.BigIntegerField(verbose_name='Пин код теста')),
            ],
            options={
                'verbose_name': 'Игрок',
                'verbose_name_plural': 'Игроки',
            },
        ),
        migrations.CreateModel(
            name='Theme',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_ru', models.CharField(max_length=100, unique=True, verbose_name='Название теста на русском')),
                ('title_ky', models.CharField(blank=True, max_length=100, verbose_name='Название теста на кыргызском')),
                ('pin_code', models.BigIntegerField(blank=True, unique=True, verbose_name='Пин код')),
                ('count_question', models.PositiveIntegerField(default=0, verbose_name='Количество вопросов')),
                ('is_start', models.BooleanField(verbose_name='Тест начался?')),
                ('test_participants', models.ManyToManyField(blank=True, null=True, to='question.MyUser', verbose_name='Участники')),
            ],
            options={
                'verbose_name': 'Тема',
                'verbose_name_plural': 'Темы',
            },
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, upload_to='', verbose_name='Фото вопроса(необязательно)')),
                ('question_ru', models.TextField(verbose_name='Вопрос на русском')),
                ('question_ky', models.TextField(blank=True, verbose_name='Вопрос на кыргызском')),
                ('option_1_ru', models.CharField(max_length=250, verbose_name='1-Вариант на русском')),
                ('option_1_ky', models.CharField(blank=True, max_length=250, verbose_name='1-Вариант на кыргызском')),
                ('option_2_ru', models.CharField(max_length=250, verbose_name='2-Вариант на русском')),
                ('option_2_ky', models.CharField(blank=True, max_length=250, verbose_name='2-Вариант на кыргызском')),
                ('option_3_ru', models.CharField(blank=True, max_length=250, verbose_name='3-Вариант на русском')),
                ('option_3_ky', models.CharField(blank=True, max_length=250, verbose_name='3-Вариант на кыргызском')),
                ('option_4_ru', models.CharField(blank=True, max_length=250, verbose_name='4-Вариант на русском')),
                ('option_4_ky', models.CharField(blank=True, max_length=250, verbose_name='4-Вариант на кыргызском')),
                ('correct_answer', models.PositiveIntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4)], verbose_name='Правильный вариант')),
                ('time_second', models.PositiveIntegerField(default=30, verbose_name='Время в секундах')),
                ('theme', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='question.theme', verbose_name='Тема')),
            ],
            options={
                'verbose_name': 'Вопрос',
                'verbose_name_plural': 'Вопросы',
            },
        ),
    ]
